### ISSUE TITLE
“TODO: Update this diagram.”？

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis-wiki#176]
有句 TODO 直接出现在了[简介 | BIThesis](https://bithesis.bitnp.net/guide/intro.html#%E5%BC%80%E5%A7%8B%E9%98%85%E8%AF%BB%E6%96%87%E6%A1%A3) 上。

https://github.com/BITNP/BIThesis-wiki/blob/128c0f03f9bbd67055404786ced543619e731efe/wiki/guide/intro.md?plain=1#L19-L21

这一行源于[`75dfe00`](https://github.com/BITNP/BIThesis-wiki/commit/75dfe0017b64f5611e7a6ca2f3d25fadaca06087#diff-0f54bc0a350fb5f832216c71041b60aadcfcbd891373b19ed81e5dd9cc494889R21)，之前的图如下。

![](https://i.loli.net/2020/03/27/mV3kTsnCDNWwlOU.png)

**Comment by fky2015** [comment]
@spencerwooo

**Comment by spencerwooo** [comment]
了解，我来处理一下。
