### ISSUE TITLE
【讨论】是否需要从 Vercel 迁移 wiki 到 Cloudflares

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis-wiki#320]
目前 Vercel 有两个问题：
1. 绑定在我个人的账号下，未来我可能没有充足的时间维护。
2. Vercel 的生产模式需要手动去升级，没法绑定仓库里的最新 commit。

不过 Cloudflares 在大陆访问的速度可能有点难以保证？

Relates-to: [网站自动部署 · BITNP/BIThesis · Discussion #409](https://github.com/BITNP/BIThesis/discussions/409)

**Comment by everything411** [comment]
网协的主页目前也是挂在我名下的vercel里，日后也将出现类似问题。
刚才我研究了下，如下图所示Vercel无法自动部署的原因是这里同步到的分支是BITNP:master而非本仓库的master。我注意到手动在fork里点sync fork拉到的commit是master，而pull bot拉到的commit显示BITNP:master，因此换种同步github仓库的方式是否可解决此问题？
<img width="662" alt="1718082833244" src="https://github.com/BITNP/BIThesis-wiki/assets/32010059/9ee0a1be-b6e8-4b97-908e-d318eab4c81d">

**Comment by YDX-2147483647** [comment]
### [阿里云网站运维检测平台 - 网络拨测工具](https://boce.aliyun.com/detect/http)

- https://bithesis.bitnp.net/

  平均 1523.03 ms，北京市 859.50 ms。

  https://boce.aliyun.com/detect/http/0565cba741b349f684bf706477ca3a60

- https://bithesis-wiki.netlify.app/

  平均 947.60 ms，北京市 431.67 ms。

  https://boce.aliyun.com/detect/http/dca6be34c4144332bb8e204ff5791a30

- https://bithesis-wiki.pages.dev/ 

  平均 1105.95 ms，北京市 966.50 ms。

  https://boce.aliyun.com/detect/http/64825171475e4ca3bb74c0f312815cd2

**Comment by fky2015** [comment]
> 网协的主页目前也是挂在我名下的vercel里，日后也将出现类似问题。 刚才我研究了下，如下图所示Vercel无法自动部署的原因是这里同步到的分支是BITNP:master而非本仓库的master。我注意到手动在fork里点sync fork拉到的commit是master，而pull bot拉到的commit显示BITNP:master，因此换种同步github仓库的方式是否可解决此问题？ <img alt="1718082833244" width="662" src="https://private-user-images.githubusercontent.com/32010059/338445161-9ee0a1be-b6e8-4b97-908e-d318eab4c81d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTMxOTIsIm5iZiI6MTcxODA5Mjg5MiwicGF0aCI6Ii8zMjAxMDA1OS8zMzg0NDUxNjEtOWVlMGExYmUtYjZlOC00Yjk3LTkwOGUtZDMxOGVhYjRjODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA4MDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMzhkNzU0NzcxOWY1MGQ4YjRhOTZmZDVmNzJkNWM4N2Q1YWM2ZmM2NjVkYzQ4MWFjN2UzMGRkMGM3ZDVlNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dzLE2F7UtAOkWQ80AmzqrgJN0qIPyIyX7BfGPYZHWvE">

我个人感觉是因为“Pull Bot 自动合入的 PR 没有触发 Vercel 的回调函数”。

![image](https://github.com/BITNP/BIThesis-wiki/assets/16451516/cd66bd19-cfa2-492d-8380-496013c571b1)

比如上图只有我手动合入的那个 PR 才有 [Merge pull request #122 from BITNP/main](https://github.com/fky2015/BIThesis-wiki/commit/f14d905fe7d183c92e616c476651b07e2dac1e86) 字样，而其他的应该都是 PR 中提交 commit 时候的 preview 链接。

**Comment by everything411** [comment]
vercel是根据分支来决定生产还是预览，如果有一种方式让Vercel里拉到的分支是main而非BITNP:main就好了

**Comment by YDX-2147483647** [comment]
这几周决定一下？新学年又开始了。

**Comment by fky2015** [comment]
需要迁移

**Comment by YDX-2147483647** [comment]
https://github.com/BITNP/BIThesis-wiki/compare/92472ba..b77839d

https://github.com/BITNP/BIThesis-wiki/blob/b77839d287e5fa5585240aae37609cd76847f623/.github/workflows/push-to-everything411-repo.yml

https://github.com/everything411/BIThesis-wiki

**Comment by everything411** [comment]
https://github.com/BITNP/bitnp-website is also deployed through my personal account
