### ISSUE TITLE
不应推荐在linux下使用系统包管理器安装texlive

### ISSUE THREAD

**Issue by everything411** [BITNP/BIThesis-wiki#38]
使用系统包管理器（如apt）安装的texlive是由发行版重新打包的版本，因此对于使用非滚动发行的发行版的用户会安装到老版本的texlive，如ubuntu 22.04中为texlive 2021，ubuntu 20.04中为texlive 2019，而ubuntu 18.04中为texlive 2017。see https://tug.org/texlive/distro.html and https://tug.org/texlive/debian.html

同时，系统包管理器将texlive安装到系统目录中，也无法使用tlmgr更新。

**Comment by fky2015** [comment]
现在的模板中含有了 bithesis 样式文件，因此只需要环境有合适的依赖即可（2020 年之后的就可以，之前的大概率也可以）。
而且 Linux 环境下用户也可以选择按照 https://www.tug.org/texlive/quickinstall.html 中提供的方式安装最新版的 TeXLive，个人认为问题不大。

可以再文档中补充以下内容：
- 推荐用户尽量安装新版的 LaTeX 发行版
