### ISSUE TITLE
CI：缓存链接检查结果

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis-wiki#459]
现在用的是 https://github.com/gaurav-nelson/github-action-markdown-link-check ，虚警率太高了，感觉能有三分之一。

https://github.com/BITNP/BIThesis-wiki/blob/e710db7db8626265a2f9c00d8a57bd27b76bf028/.github/workflows/test.yml#L28-L32

可以考虑用同一作者的 https://github.com/UmbrellaDocs/action-linkspector 或 https://lychee.cli.rs 。

**Comment by everything411** [comment]
真的有必要每次构建都检查死链吗，我感觉按周期，比如一个月，在主分支上运行一次就行吧

**Comment by YDX-2147483647** [comment]
我认为PR也有必要。把缓存设成一月长？
