### ISSUE TITLE
开发辅助工具可能没有更新？

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis-wiki#49]
- 现有文件并不能通过`pnpm format`。

  https://github.com/BITNP/BIThesis-wiki/blob/fb0132fb208a1ee5bb61349b3c5e38e1a1b486fc/package.json#L6

- [`./.vitepress/cache`](https://vitepress.vuejs.org/config/app-configs#cachedir) 没有被忽略。

  https://github.com/BITNP/BIThesis-wiki/blob/fb0132fb208a1ee5bb61349b3c5e38e1a1b486fc/.gitignore#L2

**Comment by fky2015** [comment]
在 #51 合并以后，未来可以加入一些 GitHub Actions 去测试构建、链接的有效性、语法错误等。
