### ISSUE TITLE
（已基本解决）希望能搜索文档

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis-wiki#71]
- 如果之前看过文档，只是返回来参考某一点，就很需要搜索。
- 可以部分解决 #21 。

[VitePress 文档](https://vitepress.dev/reference/default-theme-search) 说可以使用 Algolia 或 https://github.com/emersonbottero/vitepress-plugin-search ，文档自己用的是 Algolia。

---

好像之前说要转 [Docusaurus](https://docusaurus.io/)？那边似乎也是 Algolia。

**Comment by phy25** [comment]
当然还有更懒的办法是把表单提交到 https://cn.bing.com/search?q=site%3Abithesis.bitnp.net

**Comment by fky2015** [comment]
之前因为 Algolia 免费使用需要走申请流程，感觉表单好麻烦，就没有推进。

**Comment by fky2015** [comment]
目前引入了 offline search。

- 并不能精确的分词，但是大体上能用。

**Comment by YDX-2147483647** [comment]
是否需要关闭这个 issue 呢？

**Comment by fky2015** [comment]
OK
